#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

NAME="sfc"
PROG="/usr/bin/python3"
SCRIPT="./api/app.py"  # 使用相对路径
WORKDIR="/root/sing-box-subscribe"  # 指定工作目录

start_service() {
    procd_open_instance
    # 切换工作目录后运行脚本
    procd_set_param command /bin/sh -c "cd $WORKDIR && $PROG $SCRIPT"
    procd_set_param stdout 1  # 输出日志到系统日志
    procd_set_param stderr 1
    procd_set_param respawn  # 自动重启
    procd_close_instance
}

stop_service() {
    echo "Stopping $NAME"
}
